### ISSUE TITLE
Template passed end of file at variable 'QString'.

### ISSUE THREAD

**Issue by GUEVARA1962** [ZeruLight/010Templates#1]
After installing the template with 010editor and loading "blangonga0.bin" in "events.zip" provided by wish, I get the following error message.

"line 2 Template passed end of file at variable 'QString'. "

I found the following comment in the DISCORD, is this a missing file or am I installing the template incorrectly?
![coment](https://user-images.githubusercontent.com/103841815/187574629-911ad26d-3f15-41b0-b93d-882ce3aaacaa.PNG)

**Comment by sekaiwish** [comment]
Fixed now!

**Comment by GUEVARA1962** [comment]
Thank you I'll try
